In [ ]:
import pandas as pd
import numpy as np
import sys
import sklearn
import pandas as pd
import numpy as np
import sys
import sklearn
'''from google.colab import drive
drive.mount('/content/gdrive')'''

Mounted at /content/gdrive

In [ ]:
data_Train =pd.read_csv('KDDTrain+.csv')
data_Test = pd.read_csv('KDDTest+.csv')
data_Validate=pd.read_csv('new validation project.csv')

In [ ]:
data_Train

,1,tcp,smtp,SF,1703,334,0,0.1,0.2,0.3,...,205,0.71,0.03,0.01,0.01.1,0.20,0.21,0.22,0.23,normal
0,0,tcp,smtp,SF,1250,325,0,0,0,0,...,93,0.36,0.24,0.00,0.00,0.00,0.00,0.00,0.00,normal
1,0,udp,domain_u,SF,43,131,0,0,0,0,...,232,0.91,0.01,0.00,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,klogin,S0,0,0,0,0,0,0,...,20,0.08,0.06,0.00,0.00,1.00,1.00,0.00,0.00,neptune
3,0,tcp,daytime,S0,0,0,0,0,0,0,...,15,0.06,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
4,0,tcp,http,SF,213,9186,0,0,0,0,...,255,1.00,0.00,0.00,0.01,0.00,0.00,0.03,0.03,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130925,0,tcp,http,SF,202,313,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.01,0.01,0.02,0.02,normal
130926,0,tcp,http,SF,247,312,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal
130927,0,icmp,ecr_i,SF,1480,0,0,1,0,0,...,16,0.16,0.04,0.16,0.00,0.00,0.00,0.00,0.00,pod
130928,0,tcp,http,REJ,0,0,0,0,0,0,...,1,0.00,0.07,0.00,0.00,0.00,0.00,1.00,1.00,neptune
130929,0,tcp,http,SF,242,265,0,0,0,0,...,189,0.94,0.01,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [ ]:
data_Train.columns

Index(['1', 'tcp', 'smtp', 'SF', '1703', '334', '0', '0.1', '0.2', '0.3',
       '0.4', '1.1', '0.5', '0.6', '0.7', '0.8', '0.9', '0.10', '0.11', '0.12',
       '0.13', '0.14', '1.2', '2', '0.15', '0.16', '0.17', '0.18', '1.3',
       '0.19', '1.4', '100', '205', '0.71', '0.03', '0.01', '0.01.1', '0.20',
       '0.21', '0.22', '0.23', 'normal'],
      dtype='object')

In [ ]:
columns = (['duration','protocol_type','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent'
            ,'hot','num_failed_logins','logged_in','num_compromised','root_shell','su_attempted','num_root'
            ,'num_file_creations','num_shells','num_access_files','num_outbound_cmds','is_host_login'
            ,'is_guest_login','count','srv_count','serror_rate','srv_serror_rate','rerror_rate','srv_rerror_rate'
            ,'same_srv_rate','diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count'
            ,'dst_host_same_srv_rate','dst_host_diff_srv_rate','dst_host_same_src_port_rate'
            ,'dst_host_srv_diff_host_rate','dst_host_serror_rate','dst_host_srv_serror_rate','dst_host_rerror_rate'
            ,'dst_host_srv_rerror_rate','attack'])

In [ ]:
data_Train.columns=columns
data_Test.columns=columns
data_Validate.columns=columns
data_Test

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack
0,0,tcp,ftp_data,SF,1766,0,0,0,0,0,...,42,0.21,0.02,0.21,0.05,0.0,0.0,0.00,0.00,normal
1,0,tcp,http,SF,301,24222,0,0,0,0,...,255,1.00,0.00,0.03,0.03,0.0,0.0,0.00,0.00,normal
2,3,tcp,pop_3,SF,30,93,0,0,0,0,...,211,0.83,0.02,0.00,0.00,0.0,0.0,0.04,0.00,guess_passwd
3,0,tcp,http,SF,245,389,0,0,0,0,...,255,1.00,0.00,0.02,0.02,0.0,0.0,0.00,0.00,normal
4,0,tcp,private,RSTR,0,0,0,0,0,0,...,1,0.00,0.89,0.88,0.00,0.0,0.0,0.90,1.00,portsweep
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21410,0,tcp,http,SF,54540,8314,0,0,0,2,...,254,1.00,0.01,0.00,0.00,0.0,0.0,0.04,0.04,back
21411,0,tcp,http,SF,225,309,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,normal
21412,0,udp,private,SF,47,47,0,0,0,0,...,255,1.00,0.00,0.01,0.00,0.0,0.0,0.00,0.00,snmpguess
21413,0,tcp,http,SF,330,28334,0,0,0,0,...,255,1.00,0.00,0.05,0.02,0.0,0.0,0.00,0.00,normal
21414,0,udp,private,SF,105,146,0,0,0,0,...,9,1.00,0.00,0.11,0.00,0.0,0.0,0.00,0.00,normal

In [ ]:
data_Train.isnull().sum()
data_Test.isnull().sum()

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
attack                         0
dtype: int64

In [ ]:
data_Train['attack'].value_counts()

normal             66085
neptune            40622
satan               4152
ipsweep             3530
smurf               3112
portsweep           2925
nmap                1482
back                1241
guess_passwd        1216
mscan                942
warezmaster          921
teardrop             864
warezclient          832
apache2              708
processtable         645
snmpguess            315
saint                288
mailbomb             280
pod                  231
snmpgetattack        172
httptunnel           130
buffer_overflow       48
land                  23
rootkit               22
multihop              22
named                 16
ps                    14
sendmail              14
xterm                 12
imap                  12
ftp_write             11
loadmodule            11
xlock                  9
phf                    6
perl                   5
xsnoop                 4
worm                   2
sqlattack              2
udpstorm               2
spy                    2
Name: attack, dtype: int64

In [ ]:
data_obj = data_Train.select_dtypes(['object']).columns

In [ ]:
data_Train["attack"].value_counts()

normal             66085
neptune            40622
satan               4152
ipsweep             3530
smurf               3112
portsweep           2925
nmap                1482
back                1241
guess_passwd        1216
mscan                942
warezmaster          921
teardrop             864
warezclient          832
apache2              708
processtable         645
snmpguess            315
saint                288
mailbomb             280
pod                  231
snmpgetattack        172
httptunnel           130
buffer_overflow       48
land                  23
rootkit               22
multihop              22
named                 16
ps                    14
sendmail              14
xterm                 12
imap                  12
ftp_write             11
loadmodule            11
xlock                  9
phf                    6
perl                   5
xsnoop                 4
worm                   2
sqlattack              2
udpstorm               2
spy                    2
Name: attack, dtype: int64

In [ ]:
data_obj

Index(['protocol_type', 'service', 'flag', 'attack'], dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder
protocol_type_le = LabelEncoder()
service_le = LabelEncoder()
flag_le = LabelEncoder()

In [ ]:
data_Train['protocol_type'] = protocol_type_le.fit_transform(data_Train['protocol_type'])
data_Train['service'] = service_le.fit_transform(data_Train['service'])
data_Train['flag'] = flag_le.fit_transform(data_Train['flag'])
data_Test['protocol_type'] = protocol_type_le.fit_transform(data_Test['protocol_type'])
data_Test['service'] = service_le.fit_transform(data_Test['service'])
data_Test['flag'] = flag_le.fit_transform(data_Test['flag'])
data_Validate['protocol_type'] = protocol_type_le.fit_transform(data_Validate['protocol_type'])
data_Validate['service'] = service_le.fit_transform(data_Validate['service'])
data_Validate['flag'] = flag_le.fit_transform(data_Validate['flag'])

In [ ]:
data_Test

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack
0,0,1,19,9,1766,0,0,0,0,0,...,42,0.21,0.02,0.21,0.05,0.0,0.0,0.00,0.00,normal
1,0,1,22,9,301,24222,0,0,0,0,...,255,1.00,0.00,0.03,0.03,0.0,0.0,0.00,0.00,normal
2,3,1,43,9,30,93,0,0,0,0,...,211,0.83,0.02,0.00,0.00,0.0,0.0,0.04,0.00,guess_passwd
3,0,1,22,9,245,389,0,0,0,0,...,255,1.00,0.00,0.02,0.02,0.0,0.0,0.00,0.00,normal
4,0,1,45,4,0,0,0,0,0,0,...,1,0.00,0.89,0.88,0.00,0.0,0.0,0.90,1.00,portsweep
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21410,0,1,22,9,54540,8314,0,0,0,2,...,254,1.00,0.01,0.00,0.00,0.0,0.0,0.04,0.04,back
21411,0,1,22,9,225,309,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,normal
21412,0,2,45,9,47,47,0,0,0,0,...,255,1.00,0.00,0.01,0.00,0.0,0.0,0.00,0.00,snmpguess
21413,0,1,22,9,330,28334,0,0,0,0,...,255,1.00,0.00,0.05,0.02,0.0,0.0,0.00,0.00,normal
21414,0,2,45,9,105,146,0,0,0,0,...,9,1.00,0.00,0.11,0.00,0.0,0.0,0.00,0.00,normal

In [ ]:
df_train=data_Train.copy(deep=True)
df_test=data_Test.copy(deep=True)
df_validate=data_Validate.copy(deep=True)

In [ ]:
l1=['normal','dos','probe','u2r','r2l']
tdf=df_train['attack']
nwdf=tdf.replace({ 'normal' : l1[0], 'neptune' : l1[1] ,'back': l1[1], 'land': l1[1], 'pod': l1[1], 'smurf': l1[1], 'teardrop': l1[1],'mailbomb': l1[1], 'apacl1[1]he2': l1[1], 'processtable': l1[1], 'udpstorm': l1[1], 'worm': l1[1],
                           'ipsweep' : l1[2],'nmap' : l1[2],'portsweep' : l1[2],'satan' : l1[2],'mscan' : l1[2],'saint' : l1[2]
                           ,'ftp_write': l1[3],'guess_passwd':l1[3],'imap': l1[3],'multihop': l1[3],'phf': l1[3],'spy': l1[3],'warezclient': l1[3],'warezmaster': l1[3],'sendmail': l1[3],'named': l1[3],'snmpgetattack': l1[3],'snmpguess': l1[3],'xlock': l1[3],'xsnoop': l1[3],'httptunnel': l1[3],
                           'buffer_overflow': l1[4],'loadmodule': l1[4],'perl': l1[4],'rootkit': l1[4],'ps': l1[4],'sqlattack': l1[4],'xterm': l1[4],
                 'mscan':l1[2], 'udpstorm':l1[1], 'xterm':l1[3], 'worm':l1[1], 'saint':l1[2], 'snmpgetattack':l1[4], 'named':l1[4], 'mailbomb':l1[4], 'apache2':l1[1], 'httptunnel':l1[4], 'ps':l1[3], 'xsnoop':l1[4], 'processtable':l1[1], 'sendmail':l1[4], 'snmpguess':l1[4], 'sqlattack':l1[3], 'xlock':l1[4]})
df_train['attack']=nwdf
l1=['normal','dos','probe','u2r','r2l']
tdf=df_test['attack']
nwdf=tdf.replace({ 'normal' : l1[0], 'neptune' : l1[1] ,'back': l1[1], 'land': l1[1], 'pod': l1[1], 'smurf': l1[1], 'teardrop': l1[1],'mailbomb': l1[1], 'apacl1[1]he2': l1[1], 'processtable': l1[1], 'udpstorm': l1[1], 'worm': l1[1],
                           'ipsweep' : l1[2],'nmap' : l1[2],'portsweep' : l1[2],'satan' : l1[2],'mscan' : l1[2],'saint' : l1[2]
                           ,'ftp_write': l1[3],'guess_passwd':l1[3],'imap': l1[3],'multihop': l1[3],'phf': l1[3],'spy': l1[3],'warezclient': l1[3],'warezmaster': l1[3],'sendmail': l1[3],'named': l1[3],'snmpgetattack': l1[3],'snmpguess': 3,'xlock': l1[3],'xsnoop': l1[3],'httptunnel': l1[3],
                           'buffer_overflow': l1[4],'loadmodule': l1[4],'perl': l1[4],'rootkit': l1[4],'ps': l1[4],'sqlattack': l1[4],'xterm': l1[4],
                 'mscan':l1[2], 'udpstorm':l1[1], 'xterm':l1[3], 'worm':l1[1], 'saint':l1[2], 'snmpgetattack':l1[4], 'named':l1[4], 'mailbomb':l1[4], 'apache2':l1[1], 'httptunnel':l1[4], 'ps':l1[3], 'xsnoop':l1[4], 'processtable':l1[1], 'sendmail':l1[4], 'snmpguess':l1[4], 'sqlattack':l1[3], 'xlock':l1[4]})
df_test['attack']=nwdf

l1=['normal','dos','probe','u2r','r2l']
tdf=df_validate['attack']
nwdf=tdf.replace({ 'normal' : l1[0], 'neptune' : l1[1] ,'back': l1[1], 'land': l1[1], 'pod': l1[1], 'smurf': l1[1], 'teardrop': l1[1],'mailbomb': l1[1], 'apacl1[1]he2': l1[1], 'processtable': l1[1], 'udpstorm': l1[1], 'worm': l1[1],
                           'ipsweep' : l1[2],'nmap' : l1[2],'portsweep' : l1[2],'satan' : l1[2],'mscan' : l1[2],'saint' : l1[2]
                           ,'ftp_write': l1[3],'guess_passwd':l1[3],'imap': l1[3],'multihop': l1[3],'phf': l1[3],'spy': l1[3],'warezclient': l1[3],'warezmaster': l1[3],'sendmail': l1[3],'named': l1[3],'snmpgetattack': l1[3],'snmpguess': 3,'xlock': l1[3],'xsnoop': l1[3],'httptunnel': l1[3],
                           'buffer_overflow': l1[4],'loadmodule': l1[4],'perl': l1[4],'rootkit': l1[4],'ps': l1[4],'sqlattack': l1[4],'xterm': l1[4],
                 'mscan':l1[2], 'udpstorm':l1[1], 'xterm':l1[3], 'worm':l1[1], 'saint':l1[2], 'snmpgetattack':l1[4], 'named':l1[4], 'mailbomb':l1[4], 'apache2':l1[1], 'httptunnel':l1[4], 'ps':l1[3], 'xsnoop':l1[4], 'processtable':l1[1], 'sendmail':l1[4], 'snmpguess':l1[4], 'sqlattack':l1[3], 'xlock':l1[4]})
df_validate['attack']=nwdf

In [ ]:
x_train=df_train.drop(['attack'],axis=1)
y_train=pd.DataFrame(df_train['attack'].copy())
x_test=df_test.drop(['attack'],axis=1)
y_test=pd.DataFrame(df_test['attack'].copy())
x_validate=df_validate.drop(['attack'],axis=1)
y_validate=pd.DataFrame(df_validate['attack'].copy())
x_train.head()
y_train.head()

   attack
0  normal
1  normal
2     dos
3     dos
4  normal

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

label_encoder = LabelEncoder()
scaler=MinMaxScaler()

x1=x_train.copy(deep=True)

scaler=MinMaxScaler()
scaler.fit(x1)
scaled_data=scaler.transform(x1)
scaled_data=pd.DataFrame(scaled_data)
scaled_data.columns= x1.columns
x_train=scaled_data

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

label_encoder = LabelEncoder()
scaler=MinMaxScaler()

x1=x_test.copy(deep=True)

scaler=MinMaxScaler()
scaler.fit(x1)
scaled_data=scaler.transform(x1)
scaled_data=pd.DataFrame(scaled_data)
scaled_data.columns= x1.columns
x_test=scaled_data

In [ ]:
label_encoder = LabelEncoder()
scaler=MinMaxScaler()
x1=x_validate.copy(deep=True)
scaler=MinMaxScaler()
scaler.fit(x1)
scaled_data=scaler.transform(x1)
scaled_data=pd.DataFrame(scaled_data)
scaled_data.columns= x1.columns
x_validate=scaled_data

In [ ]:
y_train.value_counts()

attack
normal    66085
dos       47450
probe     13319
u2r        3050
r2l        1026
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
y_train.value_counts()

attack
normal    66085
dos       47450
probe     13319
u2r        3050
r2l        1026
dtype: int64

In [ ]:
y_train.head()

   attack
0  normal
1  normal
2     dos
3     dos
4  normal

In [ ]:
#random forest algorithm
from sklearn.ensemble import RandomForestClassifier
classifier_random = RandomForestClassifier(n_estimators = 100)
classifier_random.fit(x_train, y_train)

In [ ]:
#knn algorithm
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 3)
classifier_knn.fit(x_train, y_train)

In [ ]:
#random forest classifier for feature selection
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(n_estimators= 15, criterion="gini")
classifier.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

RandomForestClassifier(n_estimators=15)

In [ ]:
x_predict=classifier.predict(x_test)

In [ ]:
x_predict

array(['normal', 'normal', 'normal', ..., 'r2l', 'normal', 'normal'],
      dtype=object)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(x_predict,y_test))

0.9723558253560588